[build-system]
requires = ["hatchling>=1.18"]
build-backend = "hatchling.build"

[project]
name = "pyheteromap"
version = "0.1.0"
description = "Subchain and GW-reference analysis for IDR trajectories (PyHeteroMap)."
readme = "README.md"
requires-python = ">=3.9,<3.11"
license = { text = "MIT" }
authors = [{ name = "Your Name" }]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: POSIX :: Linux"
]
dependencies = [
  "numpy==1.26.4",
  "pandas==2.2.2",
  "scipy==1.13.1",
  "matplotlib==3.9.1",
  "mdtraj==1.10.0",
  "afrc==0.3.4",
"biopython>=1.83"
]
[project.urls]
Homepage = "https://github.com/hshadman/IDP_Global_Local_Conformational_Landscapes"
Issues   = "https://github.com/hshadman/IDP_Global_Local_Conformational_Landscapes"
[tool.hatch.build]
include = [
  "src/pyheteromap/reference_GW_chainlength_100.csv",
]
